spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    rest:
      base-path: /api
  integration:
    management:
      default-logging-enabled: true

logging:
  level:
    root: warn
    org.springframework.security: warn

server:
  tomcat:
    max-http-response-header-size: 64KB



