spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver  # for migration

  # for R2DBC
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tacocloud
    username: postgres
    password: postgres
    pool:
      max-size: 10
      initial-size: 5

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none

taco:
  orders:
    page-size: 10
