spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver  # Настройки для JDBC, которые требуются Liquibase для выполнения миграций

  # Настройки для R2DBC
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tacocloud
    username: postgres
    password: postgres
    pool:
      max-size: 10
      initial-size: 5

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml  # Указываем путь к вашему changelog-файлу

  jpa:
    hibernate:
      ddl-auto: none  # Liquibase управляет схемой

taco:
  orders:
    page-size: 10
