spring:
  kafka:
    producer:
      bootstrap-servers: kafka:9092

  data:
    rest:
      base-path: /api
  integration:
    management:
      default-logging-enabled: true
  jpa:
    open-in-view: true
logging:
  level:
    org.apache.kafka: warn
    org.springframework.kafka: warn

taco:
  orders:
    page-size: 10

server:
  port: 8080

