version: '4.28.0'
services:
  rabbitmq:
    image: rabbitmq
    hostname: rabbit-name
    ports:
      - "15672:15672" # Порт управления RabbitMQ, если нужно

  chap_9_rabbitmq_push_listener:
    build: ./
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"