server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-password: letmein
    key-store-type: PKCS12
    key-alias: mycert

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  rsocket:
    server:
      port: 8444 # rsocket port has to be different from server port
      ssl:
        key-store: "classpath:keystore.jks"
        key-store-password: "letmein"
        key-password: "letmein"
        key-store-type: PKCS12


