apiVersion: apps/v1
kind: Deployment
metadata:
  name: tacocloud18gc  # Имя приложения
  labels:
    app: tacocloud18gc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tacocloud18gc
  template:
    metadata:
      labels:
        app: tacocloud18gc
    spec:
      containers:
        - name: tacocloud18gc
          image: gcr.io/tacocloud18gc-438613/tacocloud18gc:latest  # Правильный путь с Project ID
          imagePullPolicy: IfNotPresent

