apiVersion: v1
kind: Service
metadata:
  name: taco-cloud-service
spec:
  type: LoadBalancer
  selector:
    app: tacocloud18gc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
