spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tacoDB
  integration:
    management:
      default-logging-enabled: true
  jackson:
    time-zone: UTC

management:
  info:
    git:
      mode: full

    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    env:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health, info, beans, conditions, env, mappings, loggers, metrics
info:
  contact:
    email: support@tacocloud.com
    phone: 822-625-6831

logging:
  level:
    org.springframework.security: debug
    tacos.ingredients: info

taco:
  orders:
    page-size: 10

tacocloud:
  discount:
    code: "TACOS"
