spring:
  artemis:
    broker-url: tcp://artemis:61616
    user: admin
    password: admin

  jms:
    template:
      default-destination: tacocloud.order.queue

  data:
    rest:
      base-path: /api
  integration:
    management:
      default-logging-enabled: true

logging:
  level:
    root: info
    org.springframework.security: info

taco:
  orders:
    page-size: 10

server:
  port: 8080