tacocloud:
  email:
    host: "imap.gmail.com"
    mailbox: "INBOX"
    username: "testmail29007"
    password: "ukpk pnvh wvly wlnh"
    poll-rate: 10000
    port: 993

  api:
    url: http://localhost:8080/orders/fromEmail

management:
  health:
    mail:
      enabled: false

spring:
  main:
    web-application-type: none

logging:
  level:
    org.springframework.integration: trace
    jakarta.mail: trace
