spring:
  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: tacocloud-listeners
      auto-offset-reset: earliest
    properties:
      spring.json.trusted.packages: '*'
  integration:
    management:
      default-logging-enabled: false
  jpa:
    open-in-view: false
logging:
  level:
    root: warn
    org.springframework.kafka: warn

server:
  port: 8081


