spring:

  data:
    rest:
      base-path: /api
  integration:
    management:
      default-logging-enabled: true
  jpa:
    open-in-view: true
logging:
  level:
    root: warn
    org.springframework.security: warn

taco:
  orders:
    page-size: 10

server:
  port: 8080