spring:
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  data:
    rest:
      base-path: /api
  integration:
    management:
      default-logging-enabled: true
  jpa:
    open-in-view: true
logging:
  level:
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG

taco:
  orders:
    page-size: 10

server:
  port: 8080