spring:
  devtools:
    restart:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none # Turning off auto-creation of the scheme JPA/Hibernate
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: # your client-id
            client-secret: # your client-secret
            redirect-uri: # http://localhost:8080/login/oauth2/code/facebook
            scope:
              - email
              - public_profile

