spring:
  devtools:
    restart:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    rest:
      base-path: /api
  integration:
    management:
      default-logging-enabled: true

logging:
  file:
    name: chap_7_spring_data_rest/TacoCloudSpringDataREST.log
  logback:
    rolling policy:
      file-name-pattern: TacoCloudSpringDataREST-%d{yyyy-MM-dd}.%i.log
  level:
    root: warn
    org.springframework.security: warn

taco:
  orders:
    page-size: 10

