version: '4.33.1'
services:
  artemis:
    image: vromero/activemq-artemis
    ports:
      - "8161:8161" # Management Console
      - "61616:61616" # JMS
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin

  jms-order-sender:
    build:
      context: ./jms-order-sender
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - artemis

  jms-order-receiver:
    build:
      context: ./jms-order-receiver
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - artemis
