apiVersion: v1
kind: Service
metadata:
  name: taco-cloud-service
spec:
  type: NodePort
  selector:
    app: taco-cloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000