server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "taco-admin-client"
              client-secret: "secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:9090/login/oauth2/code/taco-admin-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:9090/"
              scopes:
                - "writeIngredients"
                - "deleteIngredients"
                - "openid"
            require-authorization-consent: true

  jmx:
    enabled: false

logging:
  file:
    name: chap_8_authorization_server/auth_server_log/TacoCloudOAuth2Server.log
  logback:
    rolling policy:
      file-name-pattern: TacoCloudOAuth2Server-%d{yyyy-MM-dd}.%i.log
  level:
    root: debug
    org.springframework.security: debug
