spring:
  application:
    name: chap_18_google-cloud
  data:
    mongodb:
      uri: mongodb://mongo:27017/tacoDB
  integration:
    management:
      default-logging-enabled: true
  jackson:
    time-zone: UTC
  lifecycle.timeout-per-shutdown-phase: 60s

server:
  shutdown: graceful

logging:
  level:
    org.springframework.security: debug
    tacos.ingredients: debug

taco:
  orders:
    page-size: 10
