spring:
  application:
    name: chap_18_google-cloud
  data:
    mongodb:
      uri: mongodb://mongo:27017/tacoDB
    redis:
      host: redis
      port: 6379
  session:
    timeout: 30m
    redis:
      namespace: taco-cloud
      flush-mode: immediate
      repository-type: default
  integration:
    management:
      default-logging-enabled: true
  jackson:
    time-zone: UTC
  lifecycle:
    timeout-per-shutdown-phase: 60s

server:
  shutdown: graceful

logging:
  level:
    org:
      springframework:
        validation: debug
        data:
          redis: debug
        session: debug
        security: debug
    tacos:
      ingredients: debug
    root: debug

taco:
  orders:
    page-size: 10
