spring:
  application:
    name: chap_18_google-cloud
  data:
    mongodb:
      host: mongo    # Name of service MongoDB in Kubernetes cluster
      port: 27017
      database: tacoDB
  integration:
    management:
      default-logging-enabled: true
  jackson:
    time-zone: UTC
  lifecycle.timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful

logging:
  level:
    org.springframework.security: debug
    tacos.ingredients: debug

taco:
  orders:
    page-size: 10

