spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: chap_18_google-cloud
  jmx:
    enabled: true
  data:
    mongodb:
      host: mongo    # Name of service MongoDB in Kubernetes cluster
      port: 27017
      database: tacoDB
  integration:
    management:
      default-logging-enabled: true
  jackson:
    time-zone: UTC
  lifecycle.timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful

management:
  info:
    java:
      enabled: true
    git:
      enabled: true
      mode: full
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true  # checking liveness & readiness endpoints

  health:
    livenessstate:
      enabled: true   # adding liveness endpoint
    readinessstate:
      enabled: true   # adding readiness endpoint

  endpoints:
    jmx:
      exposure:
        include: health, info, beans, conditions, env, mappings, loggers, metrics, notes, livenessstate, readinessstate
    web:
      base-path: /management
      exposure:
        include: health, info, beans, conditions, env, mappings, loggers, metrics, notes, livenessstate, readinessstate

info:
  contact:
    email: support@tacocloud.com
    phone: 822-625-6831

logging:
  level:
    org.springframework.security: debug
    tacos.ingredients: debug

taco:
  orders:
    page-size: 10

tacocloud:
  discount:
    code: "TACOS"
