version: '4.28.0'
services:
  artemis:
    image: vromero/activemq-artemis
    ports:
      - "8161:8161" # Management Console
      - "61616:61616" # JMS
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin

  jms_message_sender:
    build:
      context: ./jms_message_sender
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - artemis

  push_message_listener:
    build:
      context: ./push_message_listener
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - artemis
