spring:
  devtools:
    restart:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    driver-class-name: org.h2.Driver

#    disabling whitelabel to render error.html
server:
  error:
    whitelabel:
      enabled: false


