
spring:
  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    template:
      default-destination: tacocloud.order.queue
    listener:
      min-concurrency: 1
      max-concurrency: 10
  integration:
    management:
      default-logging-enabled: true
  profiles:
    active: jms-listener

# spring.profiles.active=jms-listener
logging:
  level:
    root: debug
    org.springframework.security: debug

server:
  port: 8081
