spring:
  devtools:
    restart:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    rest:
      base-path: /api
  integration:
    management:
      default-logging-enabled: true
  rsocket:
    server:
      port: 9000

logging:
  file:
    name: chap_8_spring_authorization_server/TacoCloudSpringAuthorizationServer.log
  logback:
    rolling policy:
      file-name-pattern: TacoCloudSpringAuthorizationServer-%d{yyyy-MM-dd}.%i.log
  level:
    root: warn
    org.springframework.security: warn

taco:
  orders:
    page-size: 10
---

spring:
  profiles:
    active: dev
