version: '4.29.0'

services:
  authorization_server:
    build: ./authorization_server
    image: authorization_server_image
    ports:
      - "9000:9000"
    networks:
      backend_network:
        aliases:
          - authserver

  resource_server:
    build: ./resource_server
    image: resource_server_image
    depends_on:
      - authorization_server
    ports:
      - "8080:8080"
    networks:
      - backend_network

  client_app:
    build: ./client_app
    image: client_app_image
    depends_on:
      - resource_server
    ports:
      - "9090:9090"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
