spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:tacocloud
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
