version: '4.29.0'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami
    networks:
      - backend_network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper
    networks:
      - backend_network

  kafka_producer:
    build:
      context: ./kafka_producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - backend_network

  kafka_listener:
    build:
      context: ./kafka_listener
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    networks:
      - backend_network

volumes:
  kafka_data:
  zookeeper_data:

networks:
  backend_network:
    driver: bridge
