spring:
  devtools:
    restart:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: true
      path: /h2-console

  integration:
    management:
      default-logging-enabled: true

logging:
  file:
    name: chap_6_config_profile/TacoCloud.log
  logback:
    rolling policy:
      file-name-pattern: TacoCloudProfile-%d{yyyy-MM-dd}.%i.log
  level:
    root: warn
    org.springframework.security: warn

taco:
  orders:
    page-size: 10
---

spring:
  profiles:
    active: dev
