spring:
  devtools:
    restart:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: true
      path: /h2-console

  integration:
    management:
      default-logging-enabled: true


taco:
  orders:
    page-size: 10
logging:
  level:
    root: warn
    org.springframework.security: warn

---

spring:
  profiles:
    active: dev
