spring:
  artemis:
    broker-url: tcp://artemis:61616
    user: admin
    password: admin

  jms:
    template:
      default-destination: tacocloud.order.queue
    listener:
      min-concurrency: 1
      max-concurrency: 10
      auto-startup: true
      pub-sub-domain: false
  integration:
    management:
      default-logging-enabled: true
  profiles:
    active: jms-listener

# spring.profiles.active=jms-listener
logging:
  level:
    root: info
    org.springframework.security: info

server:
  port: 8081
