spring:
  rabbitmq:
    host: rabbit-name
    port: 5672

    template:
      exchange: tacocloud.order
      routing-key: kitchen.central
  devtools:
    restart:
      enabled: true

  data:
    rest:
      base-path: /api
  integration:
    management:
      default-logging-enabled: true

logging:
  level:
    root: info
    org.springframework.security: info

taco:
  orders:
    page-size: 10

server:
  port: 8080