spring:
  devtools:
    restart:
      enabled: true
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  integration:
    management:
      default-logging-enabled: true

logging:
  file:
    name: chap6-logging-config/logging/TacoCloud.log
  logback:
    rolling policy:
      file-name-pattern: TacoCloud-%d{yyyy-MM-dd}.%i.log
  level:
    root: WARN
    org.springframework.security: DEBUG
taco:
  orders:
    page-size: 10
