version: '4.33.1'

services:
  zookeeper:
    image: bitnami/zookeeper:3.4.10
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami
    networks:
      - backend_network

  kafka:
    image: bitnami/kafka:2.8.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper
    networks:
      - backend_network

  kafka-producer:
    build:
      context: ./kafka-producer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - backend_network

  kafka-listener:
    build:
      context: ./kafka-listener
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    networks:
      - backend_network

volumes:
  kafka_data:
  zookeeper_data:

networks:
  backend_network:
    driver: bridge

